name: Check URLs in Markdown Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_urls:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Check URLs
      run: |
        bash check_urls.sh
